#!/bin/sh /etc/rc.common
# notApollo init script for OpenWrt
# Manages the diagnostic webpage service

START=99
STOP=10

USE_PROCD=1
PROG="/usr/sbin/uhttpd"
CONF="/etc/config/notapollo"

start_service() {
    config_load notapollo
    
    local enabled
    config_get_bool enabled main enabled 1
    [ "$enabled" -eq 0 ] && return 1
    
    procd_open_instance notapollo
    procd_set_param command $PROG -f -h /www/notapollo -r notApollo -x /cgi-bin -t 60 -T 30 -k 20 -A 1 -n 3 -N 100 -R -p 192.168.69.1:8080 -p 192.168.70.1:8080
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "notapollo"
}

reload_service() {
    stop
    start
}